#This is workflow file for windows
name: build-and-deploy

#execute the action on following events
on:
  push:
    branches: [ main ]

#this workflow has two jobs 1) to build and 2) to deploy
jobs:
  build:
    name: build-windows
    runs-on: [ self-hosted ]    
        
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: build
      run: |
        echo "this action will run on self hosted windows system"
        echo github.event_name: ${{ github.event_name }}
        echo github.workspace: ${{ github.workspace }}
        cd ${{ github.workspace }}
        gmake all
        
    - name: test
      run: |
        cd ${{ github.workspace }}\bin
        sample.exe
