#This is workflow file for windows
name: build-and-deploy

#execute the action on following events
on:
  push:
    branches: [ main ]

#this workflow has two jobs 1) to build and 2) to deploy
jobs:
  build:
    name: build-windows
    runs-on: [ windows-latest ]    
        
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: build
      run: |
        echo "this action will run on self hosted windows system"
        echo github.event_name: ${{ github.event_name }}
        echo github.workspace: ${{ github.workspace }}
        cd ${{ github.workspace }}
        gmake all
        mkdir build
        copy sample.exe build\
        
    - name: test
      run: |
        cd ${{ github.workspace }}\build
        .\sample.exe
        

    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Deploy binary to S3
      run: |
        cd ${{ github.workspace }}
        echo Bucket: ${{ secrets.AWS_S3_BUCKET }}
        aws s3 sync ./build/ s3://${{ secrets.AWS_S3_BUCKET }} --delete
