#This is workflow file for windows
name: build-and-deploy

#execute the action on following events
on:
  push:
    branches: [ main ]

#this workflow has two jobs 1) to build and 2) to deploy
jobs:
  build:
    name: build-windows
    runs-on: [ self-hosted ]    
        
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: build
      run: |
        echo "this action will run on self hosted windows system"
        echo github.event_name: ${{ github.event_name }}
        echo github.workspace: ${{ github.workspace }}
        cd ${{ github.workspace }}
        gmake all
        mkdir build
        copy sample.exe build\
        
    - name: test
      run: |
        cd ${{ github.workspace }}\build
        .\sample.exe
        

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_STAGING_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "build"
